=

== References
* See: https://www.planttext.com/
* Main reference: https://plantuml.com/state-diagram

== Grevnyrch Logging Standard Logger - User Workflow
[plantuml, target=diagram-classes, format=png]
....
@startuml
Title GLSL User Workflow

State "User Joins Site" as  UserJoins
State "User Specifies Target & Inner-bracket Info" as UserSpecifiesTargetAndInnerBracketInfo


[*] -down-> UserJoins


State "Ledger Editing Loop" as LedgerLoop {
  UserJoins -down-> SelectDropDownOrButton
  UserJoins -down-> TargetIsInputted

  State "Select Drop Down or Button" as SelectDropDownOrButton
  State "Bracket Button" as BracketButton
  State "Drop Down Bracket" as DropDownBracket 
  State "addBracket()" as addBracket
  
  State "User Inputs Target" as TargetIsInputted
  
  


  SelectDropDownOrButton -down-> DropDownBracket
  SelectDropDownOrButton -down-> BracketButton
  BracketButton --> addBracket

  TargetIsInputted -[dashed]> BracketButton
  TargetIsInputted -[dashed]> DropDownBracket

  DropDownBracket --> PressesLedgerItButton

  PressesLedgerItButton -down-> LedgerIt
  
  addBracket --> SetupTargetsBasedOnBracketPick
  SetupTargetsBasedOnBracketPick --> UserSpecifiesTargetAndInnerBracketInfo

}


LedgerIt -down-> [*]

UserSpecifiesTargetAndInnerBracketInfo -down> [*]
@enduml


' =======================================
' note left of UserJoins : Single line note
' note right of SelectDropDownOrButton
'    Notes can also 
'    take up multiple
'    lines like this
'end note

'UserJoins -right-> SelectDropDownOrButton
....
