=

== References
* See: https://www.planttext.com/
* Main reference: https://plantuml.com/state-diagram

== Grevnyrch Logging Standard Logger - User Workflow
[plantuml, target=diagram-classes, format=png]
....
@startuml
Title GLSL User Workflow

State "User Joins Site" as  UserJoins
State "User Specifies Target & Inner-bracket Info" as UserSpecifiesTargetAndInnerBracketInfo


[*] -down-> UserJoins


State "Ledger Editing Loop" as LedgerLoop {
  UserJoins -down-> SelectDropDownOrButton
  UserJoins -down-> TargetIsInputted
  UserJoins -down-> EnableInnerBracketIsToggled

  State "Select Drop Down or Button" as SelectDropDownOrButton
  State "Bracket Button Pressed" as BracketButton
  State "Drop Down Bracket" as DropDownBracket 
  State "addBracket()" as addBracket
  State "'Ledger It!' Button Pressed" as PressesLedgerItButton
  
  State "User Inputs Target" as TargetIsInputted
  
  


  SelectDropDownOrButton -down-> DropDownBracket
  SelectDropDownOrButton -down-> BracketButton
  BracketButton --> addBracket

  TargetIsInputted -[dashed]> addBracket
  TargetIsInputted -[dashed]> LedgerIt

  DropDownBracket --> PressesLedgerItButton

  PressesLedgerItButton -down-> LedgerIt
  
  addBracket --> SetupTargetsBasedOnBracketPick
  SetupTargetsBasedOnBracketPick --> LedgerIt

  LedgerIt: 1. Push Back current Ledger
  LedgerIt: 2. Get Current Bracket
  LedgerIt: 3. Determine Bracket Size + Width
  LedgerIt: 4. Determine Target
  
  state LedgerIt {
    state addTo <<choice>>
    
    state "5. Determine Bracket Config" as DetermineBracketConfigs
    DetermineBracketConfigs --> addTo
    addTo --> MinorId : [isLedgerEmpty || !isInnerBracketToggled]
    addTo --> MajorId : [else]  
    'addTo --> MinorId : [isLedgerEmpty || !isInnerBracketToggled]
    'addTo --> MajorId : [else]  
  }

}

State "User Menu Input" as UserMenuInput {

  UserJoins -> TargetMenu
  UserJoins -> LogMenu

}

LedgerIt -down-> [*]

UserSpecifiesTargetAndInnerBracketInfo -down> [*]
@enduml


' =======================================
' note left of UserJoins : Single line note
' note right of SelectDropDownOrButton
'    Notes can also 
'    take up multiple
'    lines like this
'end note

'UserJoins -right-> SelectDropDownOrButton
....
