=

== References
* See: https://www.planttext.com/
* Main reference: https://plantuml.com/state-diagram

== Grevnyrch Logging Standard Logger - User Workflow
[plantuml, target=diagram-classes, format=png]
....
@startuml
Title GLSL User Workflow

State "User Joins Site" as  UserJoins
State "User Specifies Target & Inner-bracket Info" as UserSpecifiesTargetAndInnerBracketInfo


[*] -down-> UserJoins


State "Log Entries" as LogEntries {
  State "0. Initialization" as Init {
    State "Enable: InnerBracketIsToggled" as EnableInnerBracketIsToggled
  }
  
  Init --down[dashed]-> LedgerLoop
  
  State "1. Ledger Editing Loop" as LedgerLoop {

    State "Start Ledger Editing" as LedgerStart
    UserJoins -down-> LedgerStart
  
    LedgerStart -[dashed]-> LedgerLoopForm
    LedgerStart -[dashed]-> LedgerLoopButtons
  
    State "Form" as LedgerLoopForm {
      State "User: Selects Bracket Drop Down" as SelectDropDown
      SelectDropDown -down[dashed]-> DropDownBracket
    
      State "Drop Down Bracket" as DropDownBracket 
      DropDownBracket --> PressesLedgerItButton      
    }
    
    State "Buttons" as LedgerLoopButtons {
      State "Bracket Button Pressed" as BracketButton
      BracketButton --> PressesLedgerItButton
    }
  
  }

  LedgerLoop -right[dashed]->TargetAdding
  TargetAdding --up--> LedgerLoop
  
  State "2. Target Adding" as TargetAdding {
    UserJoins -[dashed]-> TargetIsInputted

    State "User Inputs Target" as TargetIsInputted
    TargetIsInputted -left[dashed]-> LedgerIt
  }

  

  State "3. 'Ledger It!' Button Pressed" as PressesLedgerItButton{
    PressesLedgerItButton -down-> LedgerIt
  }


}

    PressesLedgerItButton --> addBracket


State "Usage/Async I/O Functions" as AsyncFunctions {

  LedgerIt: 1. Push Back current Ledger
  LedgerIt: 2. Get Current Bracket
  LedgerIt: 3. Determine Bracket Size + Width
  LedgerIt: 4. Determine Target

  state "Bracket Adds" as Brackets {
    State "addBracket()" as addBracket
    TargetIsInputted -[dashed]> addBracket

    addBracket --> SetupTargetsBasedOnBracketPick
    SetupTargetsBasedOnBracketPick --> LedgerIt
  
  }

  state LedgerIt {
    state addTo <<choice>>
    
    state "5. Determine Bracket Config" as DetermineBracketConfigs
    DetermineBracketConfigs --> addTo
    addTo --> MinorId : [isLedgerEmpty || !isInnerBracketToggled]
    addTo --> MajorId : [else]  
    'addTo --> MinorId : [isLedgerEmpty || !isInnerBracketToggled]
    'addTo --> MajorId : [else]  
  }

}


State "User Menu Input" as UserMenuInput {

  UserJoins -> TargetMenu
  UserJoins -> LogMenu

}

LedgerIt -down-> [*]

UserSpecifiesTargetAndInnerBracketInfo -down> [*]
@enduml


' =======================================
' note left of UserJoins : Single line note
' note right of SelectDropDownOrButton
'    Notes can also 
'    take up multiple
'    lines like this
'end note

'UserJoins -right-> SelectDropDownOrButton
.... 